name: dbt CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-dbt-tests:
    runs-on: windows-latest

    env:
      DBT_PROFILES_DIR: ./ci_profiles

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        shell: pwsh
        run: |
          python -m pip install --upgrade pip
          pip install dbt-core dbt-synapse

      - name: Create dbt profiles.yml
        shell: pwsh
        run: |
          # create folder
          New-Item -ItemType Directory -Force -Path ci_profiles | Out-Null

          # create profiles.yml using a PowerShell here-string
          $content = '
empower_project:
  target: dev
  outputs:
    dev:
      type: synapse
      driver: ODBC Driver 18 for SQL Server
      server: eb-outdoorlightingperspective-workspace.sql.azuresynapse.net
      port: 1433
      database: OLP
      schema: DBT_SL
      encrypt: true
      trust_cert: true
      threads: 1
      authentication: ActiveDirectoryServicePrincipal
      client_id: ${{ secrets.AZURE_CLIENT_ID }}
      client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      tenant_id: ${{ secrets.AZURE_TENANT_ID }}
'